### ISSUE TITLE
Not Android Support

### ISSUE THREAD

**Issue by josemiguelhpz** [Anuken/GDXGifRecorder#4]
Library uses javax.imageio and java.awt which are not part of the Android platform so i get the following error when i try to run it in android:
`...E/AndroidRuntime: FATAL EXCEPTION: Thread-3
    java.lang.NoClassDefFoundError: Failed resolution of: Ljavax/imageio/ImageIO;
        at io.anuke.gif.GifRecorder.compileGIF(GifRecorder.java:354)
        at io.anuke.gif.GifRecorder.access$200(GifRecorder.java:23)
        at io.anuke.gif.GifRecorder$1.run(GifRecorder.java:335)
        at java.lang.Thread.run(Thread.java:919)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "javax.imageio.ImageIO" on path: DexPathList[[zip file ...`

**Comment by Anuken** [comment]
Indeed, java.awt isn't supported on Android, and as far as I'm aware there are no good alternatives. Packaging `ffmpeg` natives with the recorder is probably possible, but it's a non-trivial amount of work and will increase library size significantly. Even if the recorder *did* work on Android, you'd need to implement your own touch controls, as the defaults are all keyboard-based.

I don't use libGDX anymore, so this library is essentially dead - I'll probably be archiving the repo at some point.
